// imgData.js

export const startersArr = [
  {
    id: "app00",
    title: "Seaweed Salad",
    price: "$10.00",
    urls: "../img/Appetizers01s.jpg",
    intro: "Fresh seaweed with light sesame dressing.",
  },
  {
    id: "app01",
    title: "Fresh Walnut Salad",
    price: "$10.00",
    urls: "../img/Appetizers02s.jpg",
    intro: "Crisp greens with crunchy walnuts.",
  },
  {
    id: "app02",
    title: "Salmon and Bean Sprout Salad",
    price: "$18.00",
    urls: "../img/Appetizers03s.jpg",
    intro: "Tender salmon with fresh bean sprouts.",
  },
  {
    id: "app03",
    title: "Scallion Oil Abalone",
    price: "$35.00",
    urls: "../img/Appetizers04s.jpg",
    intro: "Abalone drizzled with fragrant scallion oil.",
  },
  {
    id: "app04",
    title: "Orange Shrimp Salad with Avocado",
    price: "$16.00",
    urls: "../img/Appetizers05s.jpg",
    intro: "Shrimp and avocado with citrus dressing.",
  },
  {
    id: "app05",
    title: "Red Dates and Tremella Soup",
    price: "$10.00",
    urls: "../img/Appetizers06s.jpg",
    intro: "Sweet soup with red dates and tremella.",
  },
  {
    id: "app06",
    title: "Plum Cherry Tomatoes",
    price: "$12.00",
    urls: "../img/Appetizers07s.jpg",
    intro: "Cherry tomatoes in sweet plum sauce.",
  },
  {
    id: "app07",
    title: "Coconut Cucumber Jelly",
    price: "$12.00",
    urls: "../img/Appetizers08s.jpg",
    intro: "Chilled cucumber jelly with coconut flavor.",
  },
  {
    id: "app08",
    title: "Osmanthus Lotus Root",
    price: "$15.00",
    urls: "../img/Appetizers09s.jpg",
    intro: "Lotus root in sweet osmanthus syrup.",
  },
];

export const mainsArr = [
  {
    id: "main001",
    title: "Eel Fillet",
    price: "$35.00",
    urls: "../img/MainCourses01s.jpg",
    intro: "Grilled eel fillet with savory glaze.",
  },
  {
    id: "main002",
    title: "Grilled Lamb Shoulder",
    price: "$24.00",
    urls: "../img/MainCourses02s.jpg",
    intro: "Juicy lamb shoulder grilled to perfection.",
  },
  {
    id: "main003",
    title: "Steamed Grouper",
    price: "$25.00",
    urls: "../img/MainCourses03s.jpg",
    intro: "Fresh grouper steamed with ginger and soy.",
  },
  {
    id: "main004",
    title: "Garlic Vermicelli Lobster",
    price: "$25.00",
    urls: "../img/MainCourses04s.jpg",
    intro: "Lobster over vermicelli in garlic sauce.",
  },
  {
    id: "main005",
    title: "Green Pepper Chicken Wings",
    price: "$12.00",
    urls: "../img/MainCourses05s.jpg",
    intro: "Crispy wings tossed with green peppers.",
  },
  {
    id: "main006",
    title: "Black Pepper and Garlic Beef",
    price: "$15.00",
    urls: "../img/MainCourses06s.jpg",
    intro: "Beef stir-fried with black pepper and garlic.",
  },
  {
    id: "main007",
    title: "Fried Octopus with Vegetables",
    price: "$25.00",
    urls: "../img/MainCourses07s.jpg",
    intro: "Crispy octopus with seasonal vegetables.",
  },
  {
    id: "main008",
    title: "Fried Sea Cucumber with Vegetables",
    price: "$35.00",
    urls: "../img/MainCourses08s.jpg",
    intro: "Sea cucumber stir-fried with vegetables.",
  },
  {
    id: "main009",
    title: "Sweet and Sour Pork with Pineapple",
    price: "$18.00",
    urls: "../img/MainCourses09s.jpg",
    intro: "Pork in sweet sauce with pineapple chunks.",
  },
];

export const vegetarianArr = [
  {
    id: "veg01",
    title: "Vegetable Spring Rolls",
    price: "$10.00",
    urls: "../img/Vegetarian01s.jpg",
    intro: "Crispy rolls stuffed with fresh vegetables.",
  },
  {
    id: "veg02",
    title: "Stir-fried Vegetables",
    price: "$12.00",
    urls: "../img/Vegetarian02s.jpg",
    intro: "Mixed vegetables stir-fried with light seasoning.",
  },
  {
    id: "veg03",
    title: "Cold Cowpea Salad",
    price: "$10.00",
    urls: "../img/Vegetarian03s.jpg",
    intro: "Chilled cowpeas with garlic dressing.",
  },
  {
    id: "veg04",
    title: "Fried Okra with Green Peppers",
    price: "$10.00",
    urls: "../img/Vegetarian04s.jpg",
    intro: "Crispy okra stir-fried with green peppers.",
  },
  {
    id: "veg05",
    title: "Spicy Tofu Pudding",
    price: "$8.00",
    urls: "../img/Vegetarian05s.jpg",
    intro: "Soft tofu in spicy chili sauce.",
  },
  {
    id: "veg06",
    title: "Fruit Dumplings",
    price: "$9.00",
    urls: "../img/Vegetarian06s.jpg",
    intro: "Sweet dumplings filled with fresh fruit.",
  },
  {
    id: "veg07",
    title: "Jackfruit Sticky Rice",
    price: "$14.00",
    urls: "../img/Vegetarian07s.jpg",
    intro: "Sticky rice served in ripe jackfruit.",
  },
  {
    id: "veg08",
    title: "Chickpea Pancakes",
    price: "$12.00",
    urls: "../img/Vegetarian08s.jpg",
    intro: "Savory pancakes made from chickpea flour.",
  },
  {
    id: "veg09",
    title: "Stir-fried Amaranth",
    price: "$9.00",
    urls: "../img/Vegetarian09s.jpg",
    intro: "Tender amaranth stir-fried with garlic.",
  },
];

export const dessertsArr = [
  {
    id: "des01",
    title: "Coconut Waffles",
    price: "$6.00",
    urls: "../img/Desserts01s.jpg",
    intro: "Crispy waffles with coconut aroma.",
  },
  {
    id: "des02",
    title: "Chocolate Cinnamon Balls",
    price: "$8.00",
    urls: "../img/Desserts02s.jpg",
    intro: "Rich chocolate balls with cinnamon spice.",
  },
  {
    id: "des03",
    title: "Blueberry Muffins",
    price: "$4.00",
    urls: "../img/Desserts03s.jpg",
    intro: "Soft muffins bursting with blueberries.",
  },
  {
    id: "des04",
    title: "Chocolate Pumpkin Bread",
    price: "$7.00",
    urls: "../img/Desserts04s.jpg",
    intro: "Moist bread with pumpkin and chocolate.",
  },
  {
    id: "des05",
    title: "Mango Cake",
    price: "$8.00",
    urls: "../img/Desserts05s.jpg",
    intro: "Light sponge cake with mango flavor.",
  },
  {
    id: "des06",
    title: "Coconut/Chocolate Egg Tart",
    price: "$8.00",
    urls: "../img/Desserts06s.jpg",
    intro: "Creamy tart with coconut or chocolate.",
  },
  {
    id: "des07",
    title: "Sweet Fruit Dumpling",
    price: "$10.00",
    urls: "../img/Desserts07s.jpg",
    intro: "Soft dumplings filled with sweet fruit.",
  },
  {
    id: "des08",
    title: "Pumpkin Bread",
    price: "$10.00",
    urls: "../img/Desserts08s.jpg",
    intro: "Soft bread with rich pumpkin taste.",
  },
  {
    id: "des09",
    title: "Purple Sweet Potato and Coconut Bread",
    price: "$10.00",
    urls: "../img/Desserts09s.jpg",
    intro: "Bread with sweet potato and coconut.",
  },
];

export const drinksArr = [
  {
    id: "drk01",
    title: "Pomegranate Wine",
    price: "$12.00",
    urls: "../img/Beverages04s.jpg",
    intro: "Sweet wine made from pomegranate fruit.",
  },
  {
    id: "drk02",
    title: "Mulberry Smoothie",
    price: "$10.00",
    urls: "../img/Beverages03s.jpg",
    intro: "Creamy smoothie with ripe mulberries.",
  },
  {
    id: "drk03",
    title: "Grapefruit Wine",
    price: "$12.00",
    urls: "../img/Beverages05s.jpg",
    intro: "Refreshing wine with grapefruit aroma.",
  },
];
